name: Trigger On Publish Release

on:
    release:
        types: [published]

jobs:
    release:
        uses: ./.github/workflows/job.release.yml
        with:
            TAG: ${{ github.ref_name }}
            DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
        secrets:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
